// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// costumes_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Icostumes_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentsuitsCollectionSchema property.
        /// </summary>
		Entities.suitsCollectionSchema CurrentsuitsCollectionSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramacostumes_Detail0 property.
        /// </summary>
		bool HasNextpanoramacostumes_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramacostumes_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramacostumes_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechcostumes_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechcostumes_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharecostumes_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharecostumes_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartcostumes_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartcostumes_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramacostumes_Detail0 command.
        /// </summary>
		ICommand Nextpanoramacostumes_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramacostumes_Detail0 command.
        /// </summary>
		ICommand Previouspanoramacostumes_Detail0 { get; }

	}
}
