// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// history_Interestingfacts ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ihistory_InterestingfactsViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentInterestingfactsHtmlControl property.
        /// </summary>
		string CurrentInterestingfactsHtmlControl { get; set; }
        /// <summary>
        /// Gets/Sets the Costumes_costumesListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.suitsCollectionSchema> Costumes_costumesListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Costumes_costumesListControlCollectionPageNumber property.
        /// </summary>
		int Costumes_costumesListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedcostumes_costumesListControlCollection property.
        /// </summary>
		Entities.suitsCollectionSchema Selectedcostumes_costumesListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the Getcostumes_costumesListControlCollectionCommand command.
        /// </summary>
		ICommand Getcostumes_costumesListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechInterestingfactsHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechInterestingfactsHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareInterestingfactsHtmlControlCommand command.
        /// </summary>
		ICommand ShareInterestingfactsHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartInterestingfactsHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartInterestingfactsHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
