// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	DataSource.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities = WPAppStudio.Entities;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// costumes_suitsCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class costumes_suitsCollection : Icostumes_suitsCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.suitsCollectionSchema> _data = new ObservableCollection<Entities.suitsCollectionSchema>
		{
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("a9122fd0-dda8-4f58-84b9-483a4482ad1c"),
                Title=@"8 Mile Soundtrack(2002)",
                Subtitle=@"Shady/Interscope",
                Image=@"\Images\Item-1c902d84-6a46-443d-91f7-3e8924ac4086.png",
                Description=@"Music from and Inspired by the Motion Picture 8 Mile is the official soundtrack to the 2002 semi-autobiographical movie 8 Mile, starring American rapper Eminem. The album was released under Shady Records, and spawned the hit single ""Lose Yourself"". It also spawned a follow up soundtrack, More Music from 8 Mile, consisting of songs that appear in 8 Mile, that were released as singles during the film's time setting of 1995. One of the songs was performed by Tupac Shakur, who would be the subject of a documentary with a soundtrack produced by Eminem, who also produced a posthumous album by Tupac.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("4dc5ee7c-a5fe-4565-acc8-a9d307913e58"),
                Title=@"Curtain Call: The Hits(2005)",
                Subtitle=@"Shady/Aftermath",
                Image=@"\Images\Item-074fec4f-83c3-414f-adb1-b2055e3e27a7.png",
                Description=@"Curtain Call: The Hits is the first greatest hits compilation album released by American rapper Eminem. It collects Eminem's most popular songs, as well as four new tracks, including a live version of ""Stan"" featuring Elton John from the 43rd Grammy Awards, plus new songs ""Fack"", ""When I'm Gone"" and ""Shake That"" featuring Nate Dogg. It was released on December 6, 2005, under Dr. Dre's Aftermath Entertainment. The album was certified double-platinum in the US, triple-platinum in Australia and the UK, and quadruple-platinum in New Zealand. It reached #1 on several charts, including the UK and US Albums Chart. Curtain Call: The Hits was released nine years after Eminem's debut studio album, Infinite.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("ee18820c-f2f3-4029-a1c5-d82a296145b4"),
                Title=@"Encore(2004)",
                Subtitle=@"Shady/Aftermath",
                Image=@"\Images\Item-4da0dc66-33ac-4939-80dd-5fe8051ae32c.png",
                Description=@"Eminem probably lost some fans with the release of his fourth solo album, Encore. The album, a sequel to The Eminem Show, was criticized for its cartoon-ish imagery and regurgitated concepts. Even though it spawned gems like the plodding political punch, ""Mosh,"" and the introspective ""Yellow Brick Road,"" it was still considered a disappointing hip-hop album by Eminem standards. In late 2005, he dropped the greatest hits set, Curtain Call, hinting at a possible retirement from rap.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("2db1cb38-fc52-4d25-ad0c-27f42f92e75a"),
                Title=@"Infinite(1996)",
                Subtitle=@"Web Entertainment",
                Image=@"\Images\Item-25f823ad-4303-42ce-9f5c-8511e285f007.png",
                Description=@"Having conquered the local rap scene in Detroit through freestyle battles, Eminem had a buzz before he had a career. The obvious setback was gaining acceptance as a Caucasian rapper in a pre-dominantly Black neighborhood. Em would later drop the laudable, Infinite LP, in '96. Naturally, he was still struggling to discover his own style. As part of his quest for uniqueness, Eminem borrowed largely from the rhyme pattern of east coast veterans AZ, Masta Ace, Redman, and Nas, on Infinite.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("d2df55f3-6c84-4568-b251-4e913b513970"),
                Title=@"Relapse(2009)",
                Subtitle=@"Shady/Aftermath",
                Image=@"\Images\Item-362f8a10-9d6c-46fb-82f2-3a136f805510.png",
                Description=@"On January 14, 2006, Eminem rekindled his relationship with Kim Mathers by taking her to the altar for the second time. D-12 member and longtime friend Proof served as the rapper's best man, while daughter Hailie played Kim's bride-of-honor. Three months after their second marriage, Eminem filed for divorce from Kim, stating that a wedding doesn't solve underlying marital problems.

In 2009, Eminem reverted to his Slim Shady persona on his comeback album Relapse. He followed it up with the therapeutic Recovery LP in June 2010.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("a7325551-bafd-43fd-9553-fdacd2c14269"),
                Title=@"The Eminem Show(2002)",
                Subtitle=@"Shady/Aftermath",
                Image=@"\Images\Item-41012ae3-b3b5-42e6-bfc1-9addb64ca152.png",
                Description=@"The Eminem Show is a reflective album, featuring Eminem's more personal and serious side. This change gives the album a lighter tone, a departure from his previous albums. One of the most noticeable changes is the generally lighter lyrical content. Over the course of the album, he touches on the issues of race in hip hop (""White America""), his childhood (""Cleanin' Out My Closet""), the United States government and terrorism (""Square Dance""), his 2000 assault on a nightclub bouncer and his following conviction (""Soldier""), his coming to terms with fate the downside of fame (""Say Goodbye Hollywood""), his status as a rapper (""Sing for the Moment""), and his relationships with his ex-wife Kim and daughter Hailie (""Hailie's Song""). Also, the song ""Say What You Say"" (featuring Dr. Dre) is an attack on Jermaine Dupri and was also the first time that The Source magazine controversy was mentioned by Eminem. Unlike The Marshall Mathers LP, The Eminem Show's release came off without significant complaints about misogyny or homophobia. Some shock-oriented and extremely explicit lyrics are still present, but for the most part they are toned down.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("16f244c5-8632-4c39-a081-1ed64124e13a"),
                Title=@"The Marshall Mathers LP(2000)",
                Subtitle=@"Aftermath",
                Image=@"\Images\Item-beb288b7-e20a-4f60-bddf-373f2df4c6f7.png",
                Description=@"Following Dre's advice, Em waited until after the multiple-platinum Marshall Mathers LP to bring his D-12 cronies along for the ride. D-12 was originally comprised of Bugz, Proof, Kon Artis, Kuniva, Swifty, Bizarre, and Eminem. The group witnessed a dark phase in their early days when Bugz (Karnail Pitts) was killed on May 21, 1999, following an altercation at a party on Detroit's Belle Isle Park. The dark days were relived on April 12, 2006, as Proof was gunned down at a Detroit club.",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("f3404d4a-d6ae-4084-99e2-2bb678ea6b3c"),
                Title=@"The Slim Shady EP(1997)",
                Subtitle=@"Web Entertainment",
                Image=@"\Images\Item-45946de9-a228-4ca6-b656-934ed87f6f32.png",
                Description=@"Some argue that Eminem's career is hinged on shock raps and controversial dispositions. After being discovered by Dr. Dre, who allegedly found Em's demo tape on the garage floor, the Detroit MC said 'hi' to the world with his comedic single, ""My Name Is."" The song sniped at pop culture icons",
			},
          new Entities.suitsCollectionSchema
            {
                Id= new Guid("155cf36a-772e-49e6-8d43-de86e875a11b"),
                Title=@"The Slim Shady LP(1999)",
                Subtitle=@"Aftermath",
                Image=@"\Images\Item-16b44c6d-e7c3-447c-aa5a-a4d18e88dfe7.png",
                Description=@"but it was only a taste of several controversies that would later fill Eminem's rap sheet. An accompanying full length, The Slim Shady LP, would go on to win the 2000 Grammy Award for Best Rap Album.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of suitsCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of suitsCollectionSchema items.</returns>
        public ObservableCollection<Entities.suitsCollectionSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.suitsCollectionSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of suitsCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of suitsCollectionSchema items.</returns>
        public ObservableCollection<Entities.suitsCollectionSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.suitsCollectionSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.suitsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.suitsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.suitsCollectionSchema Previous(Entities.suitsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.suitsCollectionSchema Next(Entities.suitsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

