// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	DataSource.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities = WPAppStudio.Entities;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// story_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class history_story : Ihistory_story 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<ul><li>Prior to his multi-platinum major debut album,<i>The Slim Shady LP</i>, Eminem already had an underground album titled<i>Infinite</i>, and reportedly sold 500 copies out of the trunk.</li><li>Eminem is the second highest selling rapper of all time, right behind the late Tupac Shakur.</li><li><div><p>In his own words""Why is it so hard for people to believe that white people are poor?! I wouldn't say I lived in a ghetto, I'd say I lived in the 'hood. The same friends I had back then are the same people on tour with me now.""</p><p>Eminem fell in love with hip-hop as a teen, dipping in and out of various rap groups. From the defunct New Jacks crew to Soul Intent, Em constantly utilized every available platform to showcase his microphone skills early on. Along with a friend named Manix, then 14 year-old Marshall would often perform in the basement under the moniker Manix and M&amp;amp;amp;M. Marshall Mathers later changed his stage name to Eminem, playing off his own initials.<br /></p></div></li></ul>";
        }
	}
}

