// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of history_Interestingfacts ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class history_InterestingfactsViewModel : ViewModelsBase.VMBase, IViewModels.Ihistory_InterestingfactsViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		private readonly IServices.ILockScreenService _lockScreenService;
		private readonly Repositories.Ihistory_story _history_story;
		private readonly Repositories.Icostumes_suitsCollection _costumes_suitsCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="history_InterestingfactsViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="history_story">The History_story.</param>
        /// <param name="costumes_suitsCollection">The Costumes_suits Collection.</param>
        public history_InterestingfactsViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService, IServices.ILockScreenService lockScreenService, Repositories.Ihistory_story history_story, Repositories.Icostumes_suitsCollection costumes_suitsCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
			_lockScreenService = lockScreenService;
			_history_story = history_story;
			_costumes_suitsCollection = costumes_suitsCollection;
        }
		
	
		private string _currentInterestingfactsHtmlControl;

        /// <summary>
        /// CurrentInterestingfactsHtmlControl property.
        /// </summary>		
        public string CurrentInterestingfactsHtmlControl
        {
            get
            {
				
                if(_currentInterestingfactsHtmlControl == null)
					_currentInterestingfactsHtmlControl = _history_story.Get();
				return _currentInterestingfactsHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentInterestingfactsHtmlControl, value);
            }
        }
	
		private ObservableCollection<Entities.suitsCollectionSchema> _costumes_costumesListControlCollection;

        /// <summary>
        /// Costumes_costumesListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.suitsCollectionSchema> Costumes_costumesListControlCollection
        {
            get
            {
				
                if(_costumes_costumesListControlCollection == null)
					_costumes_costumesListControlCollection = _costumes_suitsCollection.GetData();
				return _costumes_costumesListControlCollection;     
            }
            set
            {
                SetProperty(ref _costumes_costumesListControlCollection, value);
            }
        }
	
		private int _costumes_costumesListControlCollectionPageNumber;

        /// <summary>
        /// Costumes_costumesListControlCollectionPageNumber property.
        /// </summary>		
        public int Costumes_costumesListControlCollectionPageNumber
        {
            get
            {
				return _costumes_costumesListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _costumes_costumesListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.suitsCollectionSchema _selectedcostumes_costumesListControlCollection;

        /// <summary>
        /// Selectedcostumes_costumesListControlCollection property.
        /// </summary>		
        public Entities.suitsCollectionSchema Selectedcostumes_costumesListControlCollection
        {
            get
            {
				return _selectedcostumes_costumesListControlCollection;
            }
            set
            {
                _selectedcostumes_costumesListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Icostumes_DetailViewModel>(_selectedcostumes_costumesListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the Getcostumes_costumesListControlCollectionCommand command.
        /// </summary>
        public  void Getcostumes_costumesListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getcostumes_costumesListControlCollectionData(pageNumber);
        }
		

        private ICommand _getcostumes_costumesListControlCollectionCommand;

        /// <summary>
        /// Gets the Getcostumes_costumesListControlCollectionCommand command.
        /// </summary>
        public ICommand Getcostumes_costumesListControlCollectionCommand
        {
            get { return _getcostumes_costumesListControlCollectionCommand = _getcostumes_costumesListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getcostumes_costumesListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechInterestingfactsHtmlControlCommand command.
        /// </summary>
        public  void TextToSpeechInterestingfactsHtmlControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentInterestingfactsHtmlControl);
        }
		

        private ICommand _textToSpeechInterestingfactsHtmlControlCommand;

        /// <summary>
        /// Gets the TextToSpeechInterestingfactsHtmlControlCommand command.
        /// </summary>
        public ICommand TextToSpeechInterestingfactsHtmlControlCommand
        {
            get { return _textToSpeechInterestingfactsHtmlControlCommand = _textToSpeechInterestingfactsHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechInterestingfactsHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareInterestingfactsHtmlControlCommand command.
        /// </summary>
        public  void ShareInterestingfactsHtmlControlCommandDelegate() 
        {
				_shareService.Share(@"Interesting facts", CurrentInterestingfactsHtmlControl);
        }
		

        private ICommand _shareInterestingfactsHtmlControlCommand;

        /// <summary>
        /// Gets the ShareInterestingfactsHtmlControlCommand command.
        /// </summary>
        public ICommand ShareInterestingfactsHtmlControlCommand
        {
            get { return _shareInterestingfactsHtmlControlCommand = _shareInterestingfactsHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(ShareInterestingfactsHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartInterestingfactsHtmlControlCommand command.
        /// </summary>
        public  void PinToStartInterestingfactsHtmlControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Ihistory_InterestingfactsViewModel), CreateTileInfoInterestingfactsHtmlControl());
        }
		

        private ICommand _pinToStartInterestingfactsHtmlControlCommand;

        /// <summary>
        /// Gets the PinToStartInterestingfactsHtmlControlCommand command.
        /// </summary>
        public ICommand PinToStartInterestingfactsHtmlControlCommand
        {
            get { return _pinToStartInterestingfactsHtmlControlCommand = _pinToStartInterestingfactsHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartInterestingfactsHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
				_lockScreenService.SetLockScreen("Item-d651bd96-6e4d-435f-bf61-236be36182d3.jpg");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new ViewModelsBase.DelegateCommand(SetLockScreenCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the AboutCommand command.
        /// </summary>
        public  void AboutCommandDelegate() 
        {
				_navigationService.NavigateTo<IViewModels.IAboutViewModel>();
        }
		

        private ICommand _aboutCommand;

        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
        public ICommand AboutCommand
        {
            get { return _aboutCommand = _aboutCommand ?? new ViewModelsBase.DelegateCommand(AboutCommandDelegate); }
        }

        private void Getcostumes_costumesListControlCollectionData(int pageNumber = 0)
        {
				Costumes_costumesListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _costumes_suitsCollection.GetData(pageNumber);
                    Costumes_costumesListControlCollection = items;
				}
                else   
				{
					var items = _costumes_suitsCollection.GetData(pageNumber);
                    foreach (var item in items)                    
                        Costumes_costumesListControlCollection.Add(item);
				}
		}
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the InterestingfactsHtmlControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoInterestingfactsHtmlControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = @"Interesting facts",
                Title = @"Interesting facts",
                BackTitle = @"Interesting facts",
                BackContent = CurrentInterestingfactsHtmlControl,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-e2c6717e-5ff9-42f1-abdc-bdb215166c74.png"
            };
            return tileInfo;
        }
    }
}
