// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IDataSource.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// costumes_suitsCollection interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Icostumes_suitsCollection
    {
		ObservableCollection<Entities.suitsCollectionSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.suitsCollectionSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.suitsCollectionSchema current);
		bool HasNext(Entities.suitsCollectionSchema current);
		Entities.suitsCollectionSchema Previous(Entities.suitsCollectionSchema current);
		Entities.suitsCollectionSchema Next(Entities.suitsCollectionSchema current);
    }
}
